name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install PortAudio on macOS
        if: runner.os == 'macOS'
        run: brew install portaudio
      
      # Install dependencies using Bash on macOS
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Install dependencies using PowerShell on Windows
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
      
      # Run tests using Bash on macOS
      - name: Test with unittest (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          python -m unittest discover -s tests

      # Run tests using PowerShell on Windows
      - name: Test with unittest (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m unittest discover -s tests
